#!/usr/bin/bash

# variables
hypr_config=$HOME/.config/hypr
waybar_config=$HOME/.config/waybar
hypr_scripts=$hypr_config/scripts
waybar_scripts=$waybar_config/scripts

# notification daemon
swaync &

# waybar
waybar &
$waybar_scripts/tools/dynamic &

# wallpaper
# $scripts/wall $config/wallpapers/4.jpg &
swww-daemon &
sleep 0.1 &
./swww_randomize ../wallpapers/ &

# effects
# $scripts/rgb &

# other
/usr/lib/polkit-kde-authentication-agent-1 &
hyprpaper &
google-chrome-stable &
steam &
# for XDPH
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
systemctl --user import-environment XDG_SESSION_TYPE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME &
wl-clip-persist --clipboard regular &
wl-paste --type text -pw cliphist store &      # only text from primary
wl-paste --type text --watch cliphist store &  # only text
wl-paste --type image --watch cliphist store & # only image

# dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
notify-send -a aurora "hello $(whoami)" &
