#!/usr/bin/bash

# variables
hypr_config=$HOME/.config/hypr
quickshell_config=$HOME/.config/quickshell
hypr_scripts=$hypr_config/scripts
quickshell_scripts=$quickshell_config/scripts

/usr/lib/hyprpolkitagent &
# quickshell
caelestia shell -d &
# $quickshell_scripts/tools/dynamic &
/usr/lib/xdg-desktop-portal-hyprland &
# other
# hyprpaper &
zen-twilight &
steam &

# for XDPH
dbus-update-activation-environment --systemd --all &
systemctl --user import-environment XDG_SESSION_TYPE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME &

wl-clip-persist --clipboard regular &
wl-paste --type text -pw cliphist store &      # only text from primary
wl-paste --type text --watch cliphist store &  # only text
wl-paste --type image --watch cliphist store & # only image

# notify-send -a aurora "hello $(whoami)" &
