[mgr]
ratio = [1, 4, 3]
sort_by = "alphabetical"
sort_dir_first = true
show_hidden = true
show_symlink = true
linemode = "size_and_mtime"
scrolloff = 5

[preview]
wrap = "yes"
tab_size = 2
max_width = 1280
max_height = 720
image_delay = 30

[plugin]
prepend_previewers = [
  # Media previewer
  { mime = "{image,audio,video}/*", run = "mediainfo" },
  { mime = "application/x-subrip", run = "mediainfo" },
  # Archive previewer
  { mime = "application/*zip", run = "ouch" },
  { mime = "application/x-tar", run = "ouch" },
  { mime = "application/x-bzip2", run = "ouch" },
  { mime = "application/x-7z-compressed", run = "ouch" },
  { mime = "application/x-rar", run = "ouch" },
  { mime = "application/x-xz", run = "ouch" },
  # Torrent previewer
  { mime = "application/x-bittorrent", run = "torrent-preview" },
]

# Task management
[tasks]
micro_workers = 10
macro_workers = 25
bizarre_retry = 5
suppress_preload = false

# Input configuration
[input]
cursor_blink = true

# Opener configuration for development files
[opener]
edit = [
  { run = '$EDITOR "$@"', desc = "Edit", block = true, for = "unix" },
  { run = 'code "$@"', desc = "VS Code", for = "unix" },
  { run = 'nvim "$@"', desc = "Neovim", block = true, for = "unix" },
]
open = [
  { run = 'xdg-open "$@"', desc = "Open", for = "unix" },
]
reveal = [
  { run = 'open -R "$@"', desc = "Reveal", for = "macos" },
  { run = 'nautilus --select "$@"', desc = "Reveal", for = "linux" },
]

# File type associations
[open]
rules = [
  { name = "*.{js,ts,jsx,tsx,vue,svelte}", use = ["edit", "open"] },
  { name = "*.{py,rb,go,rs,c,cpp,h,hpp}", use = ["edit", "open"] },
  { name = "*.{json,yaml,yml,toml,xml}", use = ["edit", "open"] },
  { name = "*.{md,txt,log}", use = ["edit", "open"] },
  { name = "*.{jpg,jpeg,png,gif,bmp,webp,svg}", use = "open" },
  { name = "*.{mp4,mkv,avi,mov,wmv,flv,webm}", use = "open" },
  { name = "*.{mp3,flac,wav,aac,ogg}", use = "open" },
  { name = "*.{zip,tar,gz,bz2,xz,7z,rar}", use = "open" },
  { name = "*.pdf", use = "open" },
]
