$primary_paletteKeyColor = 028788
$secondary_paletteKeyColor = 9a6a76
$tertiary_paletteKeyColor = 99678d
$neutral_paletteKeyColor = 7f747c
$neutral_variant_paletteKeyColor = 83727f
$background = 181117
$onBackground = eddee8
$surface = 181117
$surfaceDim = 181117
$surfaceBright = 40363e
$surfaceContainerLowest = 130c12
$surfaceContainerLow = 211920
$surfaceContainer = 251d24
$surfaceContainerHigh = 30272e
$surfaceContainerHighest = 3b3239
$onSurface = eddee8
$surfaceVariant = 51424e
$onSurfaceVariant = d5c1cf
$inverseSurface = eddee8
$inverseOnSurface = 372e35
$outline = 9d8b99
$outlineVariant = 51424e
$shadow = 000000
$scrim = 000000
$surfaceTint = 72d6d7
$primary = 72d6d7
$onPrimary = 003737
$primaryContainer = 004f50
$onPrimaryContainer = 8ff3f3
$inversePrimary = 00696a
$secondary = f0b7c5
$onSecondary = 4a2530
$secondaryContainer = 673d48
$onSecondaryContainer = ffd9e1
$tertiary = efb5df
$onTertiary = 4a2243
$tertiaryContainer = b580a8
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = 8ff3f3
$primaryFixedDim = 72d6d7
$onPrimaryFixed = 002020
$onPrimaryFixedVariant = 004f50
$secondaryFixed = ffd9e1
$secondaryFixedDim = f0b7c5
$onSecondaryFixed = 31101b
$onSecondaryFixedVariant = 643b46
$tertiaryFixed = ffd7f2
$tertiaryFixedDim = efb5df
$onTertiaryFixed = 320c2d
$onTertiaryFixedVariant = 63385b
$term0 = 343434
$term1 = 769e00
$term2 = 50e2c6
$term3 = 7bfcd5
$term4 = 75b5b6
$term5 = 7aaee9
$term6 = 82d8cd
$term7 = ccdcd4
$term8 = 9aa59f
$term9 = 85b900
$term10 = 36f7d7
$term11 = ccffec
$term12 = a3c8c5
$term13 = a2c0f7
$term14 = 89ecde
$term15 = ffffff
$rosewater = f1f3e5
$flamingo = dfe0f5
$pink = bae2ff
$mauve = 63ceec
$red = 8ab5ff
$maroon = abbef0
$peach = a9daac
$yellow = d2faeb
$green = 8cf1e4
$teal = 9eedeb
$sky = 93e9ed
$sapphire = 71d6df
$blue = 59ccde
$lavender = 87d9eb
$klink = 0095a2
$klinkSelection = 0095a2
$kvisited = 008cab
$kvisitedSelection = 008cab
$knegative = 607eff
$knegativeSelection = 607eff
$kneutral = 34c359
$kneutralSelection = 34c359
$kpositive = 00bdb2
$kpositiveSelection = 00bdb2
$text = eddee8
$subtext1 = d5c1cf
$subtext0 = 9d8b99
$overlay2 = 897986
$overlay1 = 756672
$overlay0 = 62555f
$surface2 = 50454e
$surface1 = 3e343c
$surface0 = 2b2229
$base = 181117
$mantle = 181117
$crust = 171016
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
