-- Auto-generated by DMS — do not edit manually

hl.config({
	general = {
		gaps_in = 6,
		gaps_out = 6,
		border_size = 2,
		resize_on_border = false,
	},
	decoration = {
		rounding = 12,
	},
})

hl.layer_rule({
	match = { namespace = "^dms:.*$" },
	xray = true,
})

hl.layer_rule({
	match = { namespace = "^dms:bar$" },
	xray = true,
})
