-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "desc:Samsung Electric Company Odyssey G5 HK2Y100603", mode = "2560x1440@164.833", position = "0x480", scale = 1, vrr = 2, bitdepth = 10, cm = "edid" })
hl.monitor({ output = "desc:Dell Inc. DELL U2412M 4RFMK55J33BL", mode = "1920x1200@59.950", position = "2560x0", scale = 1, transform = 1, vrr = 0 })
