# name: Bongopunk Antibaryon (Dark Mode) for Fish Shell
# Based on Fluoromachine by maxmx03
# fg: #E9EAE5
# fg_alt: #8BA7A7
# bg: #090318
# bg_alt: #070216
# bg_selection: #470590
# cyan: #61E2FF
# green: #72F1B8
# orange: #FF8B39
# pink: #FC199A
# purple: #AF6DF9
# red: #FE4462
# yellow: #FFCC00
# cyan_bright: #7AEBFF
# green_bright: #8FFAC8
# orange_bright: #FF9D5C
# pink_bright: #FF4DB8
# purple_bright: #C49AFF
# red_bright: #FF2255
# yellow_bright: #FFD633
# comment: #495495
# border: #8C57C7

fish_color_normal E9EAE5
fish_color_command 61E2FF
fish_color_keyword FC199A
fish_color_quote 72F1B8
fish_color_redirection FF8B39
fish_color_end AF6DF9
fish_color_error FE4450
fish_color_param E9EAE5
fish_color_comment 495495
fish_color_selection --background=8C57C7 --bold
fish_color_search_match --background=FFCC00 --bold
fish_color_operator FF8B39
fish_color_escape FF8B39
fish_color_autosuggestion 495495
fish_color_cancel FE4450
fish_color_cwd 61E2FF
fish_color_cwd_root FF2255
fish_color_user 72F1B8
fish_color_host AF6DF9
fish_color_host_remote FC199A
fish_color_status FE4450
fish_color_option FF8B39

fish_pager_color_progress 495495
fish_pager_color_background
fish_pager_color_prefix 61E2FF
fish_pager_color_completion E9EAE5
fish_pager_color_description 495495 FF8B39
fish_pager_color_selected_background --background=470590
fish_pager_color_selected_prefix 7AEBFF
fish_pager_color_selected_completion E9EAE5
fish_pager_color_selected_description FF8B39
fish_pager_color_secondary_background
fish_pager_color_secondary_prefix 61E2FF
fish_pager_color_secondary_completion 8BA7A7
fish_pager_color_secondary_description 495495

fish_color_valid_path --underline
fish_color_history_current 7AEBFF --bold

set -g __fish_git_prompt_color_branch AF6DF9
set -g __fish_git_prompt_color_branch_detached FE4450
set -g __fish_git_prompt_color_upstream 61E2FF
set -g __fish_git_prompt_color_bare FF8B39
set -g __fish_git_prompt_color_merging FE4450
set -g __fish_git_prompt_color_cleanstate 72F1B8
set -g __fish_git_prompt_color_dirtystate FFCC00
set -g __fish_git_prompt_color_invalidstate FE4450
set -g __fish_git_prompt_color_stagedstate 72F1B8
set -g __fish_git_prompt_color_stashstate 61E2FF
set -g __fish_git_prompt_color_untrackedfiles FF8B39
set -g __fish_git_prompt_color_flags AF6DF9

